"""add room settings

Revision ID: 92051fdad7f1
Revises: 2f647107a4c2
Create Date: 2026-09-03 14:19:00.331928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92051fdad7f1'
down_revision: Union[str, Sequence[str], None] = '2f647107a4c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add columns with server defaults for existing rows
    op.add_column('rooms', sa.Column('is_private', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('rooms', sa.Column('max_members', sa.Integer(), server_default='10', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'max_members')
    op.drop_column('rooms', 'is_private')
    # ### end Alembic commands ###
